name: Build & Lint

on: push

jobs:
  Build_and_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Build Debug apk
        run: ./gradlew assembleDebug --stacktrace
      - name: Lint
        run: ./gradlew lint --stacktrace
